---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - dconf-cli
        - python3-psutil
        - git
        - htop
        - hardinfo
        - simplescreenrecorder

  - name: copy wallpaper file
    copy:
      src: files/StarrySky_Wallpaper.jpg
      dest: /usr/share/backgrounds/StarrySky_Wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: joshua
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file://usr/share/backgrounds/StarrySky_Wallpaper.jpg'"

  - name: set wallpaper position
    become_user: joshua
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'scaled'"
